### PR TITLE
Add "Can't sell equipped items" option

### PR DESCRIPTION
**Pull request by Avalancs**
Add a new option "Can't sell equipped items" in menu. When enabled, selecting an equipped item in the sell window will have a disabled button "unequip it!" instead of "sell".
menu
sell window

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Thanks for this!

@GooeyHub: add to whitelist

Would you be interested in adding something similar so the player cannot re-purchase the ship you're already in? Another case of simply disabling the button when that ship is selected.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Avalancs** [comment]
@Cervator yes, that was the next thing I wanted to look into!

**Comment by Cervator** [comment]
Tested out and merged!

I tweaked the string used for the option to make it a little shorter and a bit clearer (no double negative with "don't" + "no") - it is now "Can sell used items" does that sound fair? :-)

Thanks!

**Comment by Avalancs** [comment]
Yes, thank you :)

**Pull request merged**
