### PR TITLE
Gradle task to allow remote debugging in Eclispse.

### PR DESCRIPTION
**Pull request by scirelli**
# Description
* Gradle task to allow remote debugging in Eclispse.  
  - Run `./gradlew -DDEBUG=true run`
    Setup remote debugging on port 9099.

# Testing
1. In Eclipse create a remote debug run config.
    - Port 9099
    - localhost
2. Place breakpoints where you want them in the project.
3. Run `./gradlew -DDEBUG=true run`
4. Attach to the running JVM by running the remote debug config you created.

# Notes
I'm new to Gradle and Eclipse, I wasn't sure how step through the code with the debugger. This is how I was able to get debugging to work in Eclipse. If this is not how it's done on this project, can you point me in the right direction?

I'm using Eclipse Neon.

### Pre Pull Request Checklist:

- [ ] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [ ] Methods have been annotated with @ Nullable and @ Nonnull ([Read more](https://github.com/MovingBlocks/DestinationSol/wiki/@Nullable-&-@Nonnull-Quickstart))
- [ ] There are no errors present in the project
- [ ] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@scirelli: thanks for the PR :-) If this helps you in Eclipse then that's fine and I'll be happy to see it added.

Most (or maybe even all) current DS devs use IntelliJ, which also has the nice Android integration allowing us to test the game there. I know of Eclipse of course but am not particularly familiar with how its debugging is set up. In IntelliJ there's no added work at all - you just launch the game via the main class either regularly or in debugging mode (which auto-creates a run config for later)

Maybe the main difference is more about when an IDE delegates control to Gradle - there you may indeed need such a task for either Eclipse or IntelliJ. So that's fine and the task is great!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by scirelli** [comment]
Alright, I'll check out Intellij, sounds easier!

**Pull request merged**
