### PR TITLE
Mouse Freedom

### PR DESCRIPTION
**Pull request by SimonC4**
This no longer confines the mouse to the window. This was an annoying issue where the mouse could never leave the game when in windowed mode. The mouse is still confined when playing the game with the mouse but is unconfined when in the in-game menu.

I think this is a much better and simpler solution than changing the way the mouse cursor is drawn, which is what I was attempting in my other branch.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/2/
Hooray Jenkins reported success with all tests good!

**Comment by SimonC4** [comment]
I have noticed that the mouse can jump to a different position when opening the in-game menu when the input is "keyboard and mouse". Not sure what can be done about this. I think it is acceptable as the overall situation is much better.

**Comment by SimonC4** [comment]
Hadn't realised there was a bug raised. This is a fix for #67.

**Comment by Cervator** [comment]
freedom

Cool stuff. Will check it out after work :-)

**Comment by Cervator** [comment]
Tests out fine. And yeah I wouldn't worry about anything that small, I couldn't even notice it :-)

**Pull request merged**
