### PR TITLE
[W.I.P] Bringing people in Discord who know Destination Sol together

### PR DESCRIPTION
**Pull request by iHDeveloper**
# Description
> It's an RPC manager that takes care of the connection between [DestinationSol](https://github.com/MovingBlocks/DestinationSol) and [Discord](https://discordapp.com). The idea is showing that you are playing Destination Sol in the Discord. This will bring people who know the game together and have fun playing Destination Sol. 😁 

# Testing
> - Pull From [My Repository](https://github.com/iHDeveloper/DestinationSol) Branch `discord-rpc`
> - Run the game from the source
> - Enjoy showing other people in Discord that you are playing Destination 

### Pre Pull Request Checklist:

- [x] Create an application in the Discord Developers
- [x] Add a setting for the player to turn **off** or **on** the RPC
- [x] Add states to the game
- [ ] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [ ] There are no errors present in the project
- [ ] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))
- [ ] Test the PR

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
@GooeyHub add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Adrijaned** [comment]
Closing as stale with bugs and no work under way; in case of further work open anew.

**Comment by iHDeveloper** [comment]
@Adrijaned Can you please reopen this pull request? I'm free now to work on it and finish it 😄

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by iHDeveloper** [comment]
@Cervator The build failed due to the artifactory problem. :(

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Gooey: Test this please

@GooeyHub: test this please

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by NicholasBatesNZ** [comment]
@iHDeveloper what's the status on this? Rebasing against develop will fix that artifactory issue

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by iHDeveloper** [comment]
@NicholasBatesNZ Thank you so much. I'm gonna continue working on it. 😄

**Comment by NicholasBatesNZ** [comment]
Unfortunately this PR is now incompatible. The repo has been rebased to remove the JREs from history (significantly reducing the size).
Please reclone for any further contributions.
Sorry for the inconvenience.

**Pull request closed without merging**
