### PR TITLE
Mercs now start with weapons in their inventory

### PR DESCRIPTION
**Pull request by JGelfand**
The planets.json config file has the mercenary item listings, and neither one was starting with weapons in their inventory. I added weapons, and everything else worked ok. I also added a placeholder block for code for mercenaries equipping items dropped on them. I don't think we should have them do that, though- not having to worry about equipping mercenaries is easier for the player.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by JGelfand** [comment]
Ah yes- I should probably add that this resolves issue #109, and also that I really should have payed attention when reading #101, where @Cervator clearly stated that

>  NPC ships were no longer **equipping** stuff

(emphasis mine). 

Anyway, the next time a experienced member of the project mentions something, I'll try to pay attention XD. At least I only wasted four hours... T_T.

**Comment by Cervator** [comment]
Hehe sorry about the hassle! But thank you so much for figuring this one out :-)

**Comment by JGelfand** [comment]
Do you want to have me work on making mercenaries equip items dropped on them, or do you just want to quickly remove the placeholder and pull?

**Comment by Cervator** [comment]
Please leave the placeholder in place, it'll be good to have it handy. I'll merge this soon'ish today, catching up after having mostly missed a day or two :-)

Equipping items dropped on the mercenaries can be done as a separate issue any time later. Maybe we should add a few more options too, I never actually noticed there were only two of them enabled.

**Comment by Cervator** [comment]
Tested on both PC and Android, looking good! Thanks again :-)

**Comment by Cervator** [comment]
Oh, a Git protip as well: Whenever upstream (MovingBlocks) changes favor updating in these two ways:

* If you have no changes locally use git pull to simply add the new commits on top of your local workspace - no merge commit
* If you do have changes locally use git *rebase* to sort of sneaky merge in the upstream changes to actually appear to have happened before your changes (it moves your commits till the "head" of the branch) - no merge commit

Both of those approaches keep the history graph cleaner as it avoids merges in favor of just moving commits around cleanly :-)

So right now with this merged assuming you have nothing outstanding locally you should be able to simply pull latest from upstream (`git pull upstream develop` would be one way that would work via command line, if upstream is the name you gave a git remote link to MovingBlocks)

**Comment by JGelfand** [comment]
Thanks for the tip. I'm currently even with MovingBlocks, but next time I get behind I'll try this, I guess.

**Pull request merged**
