### PR TITLE
Fix for issue #138 "Can sell used Items: Yes" text outside of button.

### PR DESCRIPTION
**Pull request by scirelli**
# Description
> Please describe what this PR does and why it does it
* Fix for issue #138 "Can sell used Items: Yes" text outside of button.
* SolDesktop.java: Refactor member variable name c to applicationConfig.
* Changed the permissions on gradlew for *nix systems.

# Testing
> If the PR is testable, please describe how to test it here
1. Run the application.
2. New Game.
3. New Ship/Prev Ship.
4. Press **escape** key.
5. No menu text should be outside the button.

# Notes
> Include any extra notes here

### Pre Pull Request Checklist:

- [x] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [ ] Methods have been annotated with @ Nullable and @ Nonnull ([Read more](https://github.com/MovingBlocks/DestinationSol/wiki/@Nullable-&-@Nonnull-Quickstart))
- [x] There are no errors present in the project
- [x] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged and also added you to the credits! :-)

**Comment by scirelli** [comment]
Awesome. Great game, glad I found it. 

Hope you don't mind, I'm going to use it to brush up on my Java, maybe learn some Gradle... etc. etc.

**Comment by Cervator** [comment]
Absolutely! Please learn all the things and help out as you can :D

**Pull request merged**
