### PR TITLE
Updated Contributor List

### PR DESCRIPTION
**Pull request by ZPendi**
# Description
This just adds some new names to the contributors list 

# Outstanding Work
Good chance that I missed a few names, just let me know if there's anyone I missed

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Adrijaned** [comment]
dannykelemen
msteiger
oniatus
arpitkamboj
manas96

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
