### PR TITLE
Separate volume buttons for music, other sounds

### PR DESCRIPTION
**Pull request by JGelfand**
I made separate volume buttons for the music and other sound effects, per issue #97 .

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@JGelfand thanks for the fix! Very much appreciated and looks to be working great :-)

Several other pretty quick fixes like this available if you're curious, like #102 (also relates to music).

@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged and added you to the credits + DS Contributors group here on GitHub :-)

**Pull request merged**
