### PR TITLE
Initial basic setup for unit testing

### PR DESCRIPTION
**Pull request by Cervator**
Not necessarily ideal, just copy pasted from Terasology :p

Includes one wonderful test meant to surely validate all the things, so we're really already done

This may not be how we want to hook up unit testing *exactly* but it provides a workable foundation to experiment with the topic. Exact test dependencies are literally from Terasology land and may not all be needed. We could probably even bump the dependencies to the latest versions before continuing. But I'll leave that as an exercise for the reader! :-)

Edit: With this or something comparable merged we should update Jenkins as well. The PR builder at present only Gradles `jar` while the main job runs `check` and some other stuff, including amusingly jacoco (unit test coverage - without even running unit tests)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Merged in #249 from @Adrijaned to have actual sensible test. Indeed a historic moment :-)

(CodeFactor doesn't seem to be a fan of the dangling TODO comment tho!)

**Comment by Cervator** [comment]
Tested the more sane tests locally and merged. Hooked up test results in Jenkins to trigger on next build

**Pull request merged**
