### PR TITLE
Hull branch rebased again

### PR DESCRIPTION
**Pull request by Cervator**
See #28 for prior details. This just fixed some very minor conflicts.

Ping @SimonC4 @LinusVanElswijk @PrivateAlpha !

I still think we just need a few more tweaks for this to be ready, like the turrets flipping over and the broken ("empty" somehow?) mercenary at the first planet.

Speaking of I saw a hilarious turret spin over and over - had spawned on top of a hill and somehow fell off in a way leaving it spinning in the air a few times before hitting the ground.

### CODE REVIEW

**Comment by SimonC4** [comment]
I've merged in some fixes for the ships and turrets not behaving correctly. They seem to work a lot better now. 

I think all known issues to do with this branch are now fixed. It could do with some more testing though.

**Comment by Cervator** [comment]
Awesome! Thanks bunches :-)

Will try to do some testing after work or in the coming weekend

**Comment by Cervator** [comment]
Initial testing is very promising! First mercenary is fine now and the turrets stay standing!

Maybe we should finish this up and get an early beta of v1.2.0 out on Steam + Android, let it sit for a couple weeks or longer as we make more tweaks.

@PrivateAlpha @LinusVanElswijk @theotherjay - ping! Come help test!

**Comment by Cervator** [comment]
Closing as merged. Made develop new "main" branch. Also bumped the version number and set the from-source keys back to arrow keys ('D' was conflicting)

**Pull request closed without merging**
