### PR TITLE
Formic module

### PR DESCRIPTION
**Pull request by Steampunkery**
# Description
This PR adds the formic module it the game. This module has 5 ships

- Formic Small
- Formic Medium
- Formic Large
- Formic Capital
- Formic Station

# Testing
Testable by pulling the module and running the game.

# Notes
You must have the new projectiles system in your workspace for this module to work (https://github.com/MovingBlocks/DestinationSol/pull/189 <- Projectiles should be merged soon)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
You'll need to rebase this PR onto the latest develop.

Steps:
- Make a local copy of your workspace.
- Rebase normally, and pray to god it works.
- If it works, delete backup. If it doesn't, replace current workspace with backup, and go back to step 1.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
