### PR TITLE
Fixed Meshes of bus, desertBoss, desertMedium and desertSmall

### PR DESCRIPTION
**Pull request by Mpcs**
# Description
A few fixes for issue #449 

I have looked at:
- bus - old:(https://imgur.com/GzDu3uS) new:(https://imgur.com/kNexlCB)
- desertBoss - old:(https://imgur.com/DuPE8U2) new:(https://imgur.com/e7FAN4u)
- desertMedium - old:(https://imgur.com/DpEKXtf) new:(https://imgur.com/L0jcuBT)
- desertOrbiter - I think there's no need to change it since it is really small (https://imgur.com/QL35Boq)
- desertSmall - old:(https://imgur.com/3DZNLCA) new:(https://imgur.com/RyAR03Q)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
Meh, since we are at it, do the Orbiter too for good measure. Also, please throw in a comment into the issue mentioning which ships have been checked so far, for easier maintenance.

**Comment by Mpcs** [comment]
New desertOrbiter: https://imgur.com/UBd3bvz

**Comment by Adrijaned** [comment]
@GooeyHub add to whitelist.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Avalancs** [comment]
Tests out great!

**Pull request merged**
