### PR TITLE
Feature Galore!

### PR DESCRIPTION
**Pull request by vampcat**
- Added a new Federal Module: Moved all the ships/guns created by @Sigma-One to a new Federal Module. It is enabled by default, and can be seen in action by going to Sol System and admiring the FederalCapital cruising along the starry skies.
- Added multiple playerSpawnConfigs: You can now select which ship you want to spawn in - and Modules can add more spawnConfigs too! :D

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Still good :-) Merging!

Unsure if you meant to let the two changes to the debug config slide? So FPS and detailed map info is now displayed. I like the detailed map info, haven't even seen that before. And apparently I have from 4000-6000 FPS. Huh. We still need a frame limiter ... :D

**Comment by SimonC4** [comment]
@Cervator, I remember coming across this. There's no frame rate limiting when running in dev mode, based on the code [here](https://github.com/MovingBlocks/DestinationSol/blob/develop/desktop/src/org/destinationsol/desktop/SolDesktop.java#L38)

**Comment by Cervator** [comment]
Hey @SimonC4 good to hear from you :-)

Yeah that rings a bell now! Thanks

**Pull request merged**
