### PR TITLE
added schemas

### PR DESCRIPTION
**Pull request by sohil1234**
# Description
> Added Json schemas for shields and clips 

# Testing
> If the PR is testable, please describe how to test it here

# Outstanding Work
- [ ] If there is work still outstanding, please include it here
- [x] if there is nothing outstanding, remove this section.

# Notes
> Include any extra notes here

### Pre Pull Request Checklist:

- [ ] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [x] There are no errors present in the project
- [ ] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Comment by Adrijaned** [comment]
Please add description to this PR. Also, infinite in schemaClip should be boolean, and your schemas generally miss a lot of possible values. And use please schemasv7

**Comment by jellysnake** [comment]
@GooeyHub OK to test

**Comment by Adrijaned** [comment]
@GooeyHub ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Adrijaned** [comment]
I'm just going to close this, as the work seems to have been stalled on this PR and all of the contents of this PR are also presents in different PRs. (GCI)

**Pull request closed without merging**
