### PR TITLE
Add store assets

### LINKED ISSUE #419: Box art for the new steam capsule size/GOG galaxy

### PR DESCRIPTION
**Pull request by rogersachan**
# Description

This pull request fulfills #419 by adding new cover assets for Steam and Twitch.

# Notes
 The android port needs new icons to match these assets, will be done by cropping.

### CODE REVIEW

**Comment by Adrijaned** [comment]
ok to test

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
@GooeyHub : ok to test

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by rogersachan** [comment]
I've renamed the files accordingly.

**Comment by Adrijaned** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
