### PR TITLE
androidExtras branch: Desktop builds now compile and run under gestalt v7.

### PR DESCRIPTION
**Pull request by BenjaminAmos**
# Description
The pull request builds upon the [androidExtras](https://github.com/MovingBlocks/DestinationSol/tree/androidExtras) branch and allows it to compile using gestalt v7. It also includes an optimised version of the `ArchiveFileSource` class, which allows the game to load significantly faster than with the built-in one.

# Testing
#### Testing with the Desktop build
- Clone this pull request and build the game.
- The game should compile successfully and should not crash on start-up.
- Start a new game and play it through. Ensure that it does not crash at any point.
#### Testing with the Android build
- Follow the instructions [here](https://github.com/MovingBlocks/DestinationSol/pull/418#issue-297193120), but do not change the remote.
- Change the line in `build.gradle` from:
```groovy
    //println "Fetching $repo from $uri"
```
to
```groovy
    branch = 'androidExtras'
```
- Run the build and check that it does not crash on start-up
- Try to play a new game and check that it does not crash at any point

# Notes
- When making source changes and the Android facade is in your workspace, try to use the `gradlew lint` command to check that the Android build will also still run (this is built-in to the Android gradle plugin).
- Generally the testing instructions #418 can be used here for testing, with both the android build and the desktop one.
- The optimised archive classes use the `ZipFile` class, rather than `ZipInputStream` one, which makes them more performant. The `OptimisedArchiveFileSource` code was taken and modified from its original source [here](https://github.com/MovingBlocks/gestalt/blob/8ccee052c001f9dd25bf81e931fb21d59c71558a/gestalt-module/src/main/java/org/terasology/module/resources/ArchiveFileSource.java).
- The `DestinationSolModuleFactory` code was mostly taken and modified from its original source [here](https://github.com/MovingBlocks/gestalt/blob/be3de0ef763fef2b641cbf06ddc356e16980da16/gestalt-module/src/main/java/org/terasology/module/ModuleFactory.java).
- As with #433 (which this pull request can be merged into), this depends on https://github.com/MovingBlocks/DestSolAndroid/pull/2

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Works well! Thanks a bunch. Merging into `androidExtras` now :D

**Comment by Cervator** [comment]
Thank you again so very much @BenjaminAmos ! Your work remains impeccable :-) Are you aiming to participate in GCI again this year, as either student or mentor? You were a solid contender for a grand prize last year, mostly community involvement pushed the other two ahead. You certainly also have the skill and GitHub chops to mentor, even if you would rather stay off chat, so long as you can do without the extra coordination

AndroidDS

Now I just need to tidy up a couple of my messes and we should actually be able to merge this and at long last release v2.0.0 on PC, Steam, *and* Android 🎉 

Thanks @NicholasBatesNZ as well for testing, poking, and tweaking!

**Comment by BenjaminAmos** [comment]
Thank you for your kind comments.

Hopefully I will be able to enter GCI this year, although since I have many commitments to uphold at the moment, I can't say for sure. Mentoring sounds interesting (though a new experience) and I would like to find out a bit more about that, though I am not sure at the moment if I can/will volunteer. Any more information would be appreciated, though for the moment I am tentative. For the time being, assuming that I can find the time, I should be participating as a student.

Regarding community participation, I will try to work on that. Is the IRC bridged with the discord? If so, I should be able to monitor that at intervals. Also, are the #terasology and #destinationsol channels used separately, or is the preference still to use the #terasology for both?

If the `androidExtras` branch is to become the main android staging branch, then I will try to apply the following commits in another pull request:
- https://github.com/BenjaminAmos/DestinationSol/commit/f7ad8331f7a96e05adc6a56179b518a2875390d5 - This commit fixes a crash that will occur once the `androidExtras` branch is rebased against `develop`
- https://github.com/BenjaminAmos/DestinationSol/commit/59d7fda635dc080dc16f02823ce3b58b859e0159 - This commit fixes a minor UI issue where the side buttons overlap

That should bring this branch up-to-date with my latest changes.

I'm glad to see that I've helped make progress towards Destination Sol 2.0.0. I still have a couple more things that I think would help with the game but I will create separate GitHub issues for those.

**Comment by NicholasBatesNZ** [comment]
We do hope that you find the time for GCI :)
Discord, Slack and IRC are all bridged together so joining the #destination-sol IRC channel will get you to the right place. That channel does tend to be used separately from #terasology, although there is not always someone around in #destination-sol.
I think that `androidExtras` will be the main android branch, as it has a lot of progress already. As such, a PR with those fixes you mention would be greatly appreciated :)
And yes, bring forth the issues!

**Comment by Cervator** [comment]
The #destination-sol branch on IRC is *very* lonely, yes, but it does bridge to a large amount of people in Discord, and Slack too, so yeah that's fine :-) Anybody who would notice #terasology should also notice #destination-sol

That one drawback is that if you only connect via IRC you won't see the chatlog available on Discord & Slack, unless of course you use some sort of persistent IRC setup that keeps you online.

For GCI: you'd do great either as student or mentor 👍 More potential short-term rewards as a student, more potential long-term rewards as mentor - but if you can participate as a student again this year you could always mentor in the future. We'll still be around!

Mentoring is generally lurking on chat waiting for student questions and checking the GCI site for tasks awaiting review, with the usual sort of checking on a PR, testing it, providing student feedback and so on. For GCI since all tasks are small'ish that's generally easy, and the biggest challenge is if we have gaps in coverage (timezones, mentor availability, heavy traffic spikes from student activity) as opposed to any sort of technical challenge, which is more of a GSOC thing.

Another thing is helping _prepare_ GCI tasks ahead of the work period actually starting. You can do that by just writing good issues and noting if you think some are ideal for use in GCI :-)

**Pull request merged**
