### PR TITLE
Deprecated the SolMath.toInt(boolean b) method

### PR DESCRIPTION
**Pull request by Rulasmur**
And it looks like players are going to start with an extra rep now. I should really create a template file that can be programmatically copied over. Sigh

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/9/
Hooray Jenkins reported success with all tests good!

**Comment by SimonC4** [comment]
I wonder if instead of deprecating this function it might be a better option to rename the toInt function and add JavaDoc to explain what the function does. That way we don't need to redo all the places where the deprecated function is used.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/10/
Hooray Jenkins reported success with all tests good!

**Pull request closed without merging**
