### PR TITLE
moves shardbuilder to a factory

### PR DESCRIPTION
**Pull request by pollend**
I removed shard builder in favor of a factory object. This is all the builder did in the current implementation and just moving it to a static implementation seemed to make more sense. The class has no dependencies beyond those from asset. This makes a lot more sense to move over to a factory object rather then make it apart of a dependency in solGame.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
See #455

**Pull request closed without merging**
