### PR TITLE
Faction organic

### PR DESCRIPTION
**Pull request by AonoZan**
# Description
> Added new faction of ships. Made textures and .json files.

# Notes
> I have changed station to stationOrganic (new one from this faction) in "hard" system.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Heya @AonoZan and belated thanks for the PR :-)

Going to OK this PR for our bot to test, but it may need to be configured to work with a later approach. @vampcat and a few others might be able to help with that sometime

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by AonoZan** [comment]
Ok. I'll be on forums when i find some time.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested out, added @AonoZan to the credits, and merged! Woo! :D

The new organic stuff looks awesome. Well done!

And thanks @vampcat for tweaks!

**Pull request merged**
