### PR TITLE
Console enhancements

### PR DESCRIPTION
**Pull request by Malanius**
## Description

This PR contains a few console enhancements:
- adds different levels for messages printed into the console - info, warning, error
- adds different colours to log levels - white, yellow, red
- unifies console print and logging on the same level (previously was required to call `console.println()` and then log)

messages

## Testing

1. Start the game
1. Open console
1. Type command `position` - shows position info, uses original method resulting in info message without logging
1. Type command `respawn` when alive, results in warning message in yellow colour and wan level log
1. Type command `die` twice, when calling `die` when dead, results in an error message in red colour and error level log

## Outstanding Work

- [x] slightly adjust the message levels for current messages (i.e. `die` when dead shows is now an error but should be a warning)
- [x] determine which levels to use in `position` command handler (currently uses `console.println()`)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Malanius** [comment]
@Avalancs couldn't find it myself, would appreciate if someone can point me in the right direction :)

Anyway, if it worked before it shouldn't break, as the `position` command still uses the original method call for printing output, but I'd rather check as well.

**Comment by NicholasBatesNZ** [comment]
Code looks good and testing checks out :+1: 
I think that position should have info level logging and yes, die should warn instead of error.
Also I think you may have forgotten to remove those logger imports ;)
Thanks for your work

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
