### PR TITLE
Gestalt cleanup

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
Context injection via `@In`
ES foundations
Commands now work in modules
Add `build.gradle` to module .gitignore
Less android specific code: https://github.com/MovingBlocks/DestSolAndroid/pull/12
No es-perf for now as android seems to break

`groovyw module get notepad -remote NicholasBatesNZ`
https://github.com/NicholasBatesNZ/notepad

- [ ] Refactor engine to `org.destinationsol.engine` so module code isn't put in the sandbox

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by IsaacLic** [comment]
I've tested this, and everything checks out, other than the known issue with module prefabs

**Pull request merged**
