### PR TITLE
Refactoring: new hull folder structure

### PR DESCRIPTION
**Pull request by LinusVanElswijk**
All data required for a hull config is now contained within a single folder.
Adding new hulls is as simple as adding a new folder under res/configs/hulls and adding the texture, icon and properties to it.

I also tried to clean up method and attribute names in the classes that had to be changed; making them more descriptive.

There is still some future work to be done:

1) For some reason, the old files can not be erased completely. This makes the game crash on the first update, without giving any hint on what went wrong.
This is the case for config/paths/hulls.json and config/hull.json.
These are left as empty json files as a temporary solution.

2) I had to add additional functions to the PathLoader class, to bypass all hardcoded file paths. I could not change them as that would break the game in other places, that still rely on these hardcoded file paths. The PathLoader class should be removed/replaced or recoded entirely; In it currents form, it greatly hinders modifications to the file structure.

The reason I'm doing a PR with these issues still open is because these issues are not introduced by the new code. The modification to the code just made these already existing issues visible.

### CODE REVIEW

**Comment by LinusVanElswijk** [comment]
As discussed on slack, it would be better to move this into a new branch, until it is more stable.

**Comment by Cervator** [comment]
Done! It is in a plain "hull" branch now.

And yeah, there are some quirks, hehe. Considering how much changed it is good enough that the game still runs!

I was able to fly to a planet just fine (spawning myself near a maze, not the starting station), no quirks noticed on the way there. On the planet some of the objects were acting funny though. Turrets were partially spawned in the ground, some of the ships seemed to fire oddly, and one skull ship was sort of just sitting on the surface. Plinked my little starting gun at it till it went pop, along with the whole game in response, woo!

```
java.lang.AssertionError: intRnd min equals max -0.0
	at com.miloshpetrov.sol2.common.SolMath.rnd(SolMath.java:83)
	at com.miloshpetrov.sol2.common.SolMath.rnd(SolMath.java:74)
	at com.miloshpetrov.sol2.game.ship.SolShip.throwLoot(SolShip.java:310)
	at com.miloshpetrov.sol2.game.ship.SolShip.throwAllLoot(SolShip.java:281)
	at com.miloshpetrov.sol2.game.ship.SolShip.onRemove(SolShip.java:265)
	at com.miloshpetrov.sol2.game.ObjectManager.removeObjNow(ObjectManager.java:151)
	at com.miloshpetrov.sol2.game.ObjectManager.addRemove(ObjectManager.java:137)
	at com.miloshpetrov.sol2.game.ObjectManager.update(ObjectManager.java:109)
	at com.miloshpetrov.sol2.game.SolGame.update(SolGame.java:244)
	at com.miloshpetrov.sol2.SolApplication.update(SolApplication.java:102)
	at com.miloshpetrov.sol2.SolApplication.safeUpdate(SolApplication.java:83)
	at com.miloshpetrov.sol2.SolApplication.render(SolApplication.java:63)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:207)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:114)
```

**Comment by Cervator** [comment]
Bump. Lots of other stuff just merged, this thing conflicts but probably not too much and nearly works. Anybody want to give it another spin? @LinusVanElswijk you still out there?

Would like to sort this out before embarking on a bigger round of restructuring/reformatting :-)

**Comment by Cervator** [comment]
Superseded by #28 - closing

@LinusVanElswijk - ping! Curious about some of the details like if you know anything about `myHull.config.getApproxRadius()` or if you pretty much just restructured but didn't change anything.

**Comment by SimonC4** [comment]
Created PR #29 for a fix for the approximate radius.

**Pull request closed without merging**
