### PR TITLE
Gestaltify Everything! [Pt 2]

### PR DESCRIPTION
**Pull request by vampcat**
Modifies the codebase to use gestalt for loading all the assets, while also splitting up the respective items into their own files.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Re-tested, no crash, looking good! Neat to see the item drop grammar in so quick too (although I admit not having tested deep enough to validate that part, out of time tonight, aiiee)

Merged :-)

**Pull request merged**
