### PR TITLE
Finished adding the MusicManager that SimonC4 starting with menu and …

### PR DESCRIPTION
**Pull request by Rulasmur**
…ingame music.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/17/
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/18/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Awesome! Sweet to finally hear the music in-game as intended. Seems a really great fit!

One thing we should add: including the music in the volume setting or splitting it out into its own setting.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/19/
Hooray Jenkins reported success with all tests good!

**Comment by Rulasmur** [comment]
Was actually already in there, however I've made it change the volume of the currently playing music as well. Would like to separate it out and have its own slider in the future.

**Comment by Cervator** [comment]
Haven't forgotten, btw, just slammed at my day job :-)

Do we have @NeonInsect in the credits somewhere yet and/or a little copyright notice from him somewhere? Free for our use for Destination Sol but copyright him.

**Comment by NeonInsect** [comment]
yay :)

2016-03-18 6:11 GMT+01:00 Rasmus Praestholm <notifications@github.com>:

> Haven't forgotten, btw, just slammed at my day job :-)
>
> Do we have @NeonInsect <https://github.com/NeonInsect> in the credits
> somewhere yet and/or a little copyright notice from him somewhere? Free for
> our use for Destination Sol but copyright him.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/MovingBlocks/DestinationSol/pull/86#issuecomment-198210931>
>



-- 

Nils Sinatsch
Composer & Producer
www.neoninsect.de
info@neoninsect.de

**Comment by Cervator** [comment]
Tested it out again, volume settings apply correctly to music now, although we only have said option available in-game, not in the main menu, huh :-)

Thanks @Rulasmur and @SimonC4 for getting it hooked up!

@NeonInsect I added a new soundtrack section to the credits with you and the copyright disclaimer in it plus a link to your soundcloud. If you do the setup on Bandcamp or wherever let us know one or more links to add to that section, or even submit an issue/PR with the details. And thanks again for the great music!

I think this actually concludes our prep for v1.4.0 which we should test out on Android and release as a beta on Steam whenever we get a chance.

**Pull request merged**
