### PR TITLE
UiTextButtons now expand to fit their contents

### PR DESCRIPTION
**Pull request by BenjaminAmos**
# Description
This pull request resizes buttons to fit their contents. This only occurs when assigning the text to a button, so it can be overrided afterwards. It also modifies the UiVerticalListLayout to resize its content width to match the largest width of its individual elements.

# Testing
- Start the game
- Open the Play Game -> New Game menu
- Click the "Starting Ship" button multiple times to cycle through the ships
- The size of the button should change as the ship name gets larger.

# Notes
If the size of any of the buttons changes, the UiVerticalListLayout will change the size of all of the buttons, if the new size is larger than the curent size of the buttons. As such, on the New Ship screen, all the buttons may expand when selecting a new ship.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
@BenjaminAmos I'm afraid your text width getting code doesn't quite work (try putting in other scale than 1)

**Comment by BenjaminAmos** [comment]
I think that I have fixed the issue. The buttons now resize correctly when the text has a different scale. There may be some inaccuracy due to the integer cast although it appears to have a neglible effect on the actual appearance.

**Comment by vampcat** [comment]
Closing, as this PR has been covered by #346.

**Pull request closed without merging**
