### PR TITLE
JVM flag fix for mac

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
Ensures that the new `-XstartOnFirstThread` flag only runs on Mac

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Thanks for fixing my rush-job! Can confirm this tests out both on Windows and Mac :-)

Linking to #414 for reference

**Pull request merged**
