### PR TITLE
Created Nyancat ship

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
# Description
This PR adds a much needed ship to the game: Nyancat. This ship includes a custom engine and particles that enable the ship to shoot out rainbows and play the Nyancat theme as it moves.
The Nyancat image was supplied by @jellysnake and the sound was clipped from [Elfing on Soundcloud](https://soundcloud.com/elfing/nyan-cat-music)

Nyancat ship

# Testing
> You can test this by selecting "Nyancat" as your starting ship

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by NicholasBatesNZ** [comment]
I have reduced the size of the ship to better fit into the medium class and improved the collision mesh. I have also changed the rainbow engine as the old one was not ideal

New engine

**Comment by NicholasBatesNZ** [comment]
I am in the process of cleaning up my repo and will make another PR shortly

**Comment by vampcat** [comment]
@GooeyHub: ok to test

**Pull request closed without merging**
