### PR TITLE
Tribe Module Changes

### PR DESCRIPTION
**Pull request by SurajDatta**
# Description
> In this PR, I (Suraj Datta) have made a new faction of a ship (tribe) in which I have added 2 ships, serenity and serenityMedium. I am also planning to add a large ship, and move along to part 4!

# Testing
> Indeed it is very simple. you just have to run the particular code in the game after getting it to your personal directory.

# Outstanding Work
- [ ] If there is work still outstanding, please include it here
- [ ] if there is nothing outstanding, remove this section.

# Notes
> Please ignore the serenityLarge because it is an alpha version of the next ship I am working on right now.

### Pre Pull Request Checklist:

- [ ] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [ ] Methods have been annotated with @ Nullable and @ Nonnull ([Read more](https://github.com/MovingBlocks/DestinationSol/wiki/@Nullable-&-@Nonnull-Quickstart))
- [x] There are no errors present in the project
- [x] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This is much easier to review. Thanks :-)

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
Thanks for helping me how to use git!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
Hi folks, I have added a new serenity large ship with a gun and texture. Please review my work and let me know if it is ok. 
Thanks

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
Hi Guys, I have now added a new serenity capital ship. Please review my work and let me know if it is ok.
Thanks. (ps. it is very very op!)
Thanks

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request closed without merging**
