### PR TITLE
Salvage Medium w/ Faction

### PR DESCRIPTION
**Pull request by MaxBorsch**
For GCI Part 1,2,3,4,5 task of adding ships.  You can test the added HV gun by using the "Loaded Salvaged Large" start config.

I draw my artwork myself, I used pieces of other core ships however, as this faction is a "salvager" faction that builds ships from salvaged pieces...

small:
small
small

medium:
medium
medship

large:
largepic
large

capital:
cappic
capital

High Velocity Gun:
gun
Bullet looks like regular bullet, but elongated.

Station:
station
stationig
stationcol

If it's more convenient I'm fine with not having this merged until I add the remaining ships so I can keep this PR for the salvage module.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by vampcat** [comment]
@GooeyHub: ok to test

Max, you need to update to the latest develop.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by MaxBorsch** [comment]
@vampcat Rebased and fixed.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
I really like the new gun - it feels awesome, and has pretty good aim for shooting enemies while doing bullets and stuff. However, I do have one small complain - your current `Salvaged Large` config has an incompatible gun with the hull. That means by default I can't shoot anything. I would love to see at a compatible gun included with the ship by default.
(a gun is compatible/incompatible with a hull based on whether the gunSlots in that ship are fixed or not. Fixed guns only go in fixed gunSlots.)

**Comment by vampcat** [comment]
Also, the hulls are named `salvageSmall` and so on. Can you rename them to `salvagedSmall` and so on, to make more sense?

**Comment by MaxBorsch** [comment]
@vampcat Fixed.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
As you might have noticed, I moved HighVelocityGun to salvage. I remember the discussion we had, but I'm doing a cleanup and removing all guns from Core, so I thought it was a good idea to shift your gun to your module. Hope you won't mind :)

**Pull request merged**
