### PR TITLE
Android extras rebased

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
Continuation of #433 
Testing instructions [here](https://github.com/MovingBlocks/DestSolAndroid/blob/master/readMe.md)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Ship abilities do not work on Android. Not sure why

**Comment by BenjaminAmos** [comment]
I have pushed a commit fixing the module abilities in https://github.com/BenjaminAmos/DestSolAndroid/commit/70525d77c1a32554a2e7fed01494e9dc568cdc23?w=1.

Also, this code does not run under android API 24 anymore due to the use of a method that only exists under API 26. The fix for this is in https://github.com/BenjaminAmos/DestinationSol/commit/c913dd56d00631aa4574a1a8ce6f9a4baab62381.

For testing abilities in code modules, you may need to pull the latest commits from my copy of the warp repository [here](https://github.com/BenjaminAmos/warp), as they make the ability-loading code compatible with android.

For testing commands in code modules, you may want to use my [codeModuleTest](https://github.com/BenjaminAmos/codeModuleTest) module, which registers the command "TestCodeModule".

**Comment by NicholasBatesNZ** [comment]
Sorry, I just messed up your branches by not using git properly but your code works! Thanks heaps

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
🎉 M 🎉 E 🎉 R 🎉 G 🎉 E 🎉 D 🎉 !!! 🎉 

Many thanks to @BenjaminAmos and @NicholasBatesNZ in particular! Couldn't have done it without you :-)

Ad Astra!

**Pull request merged**
