### PR TITLE
Extract mercenary loading from SolGame

### PR DESCRIPTION
**Pull request by oniatus**
Refactoring which extracts mercenary loading from SolGame to a separate class.
Also includes a fix for a not properly closed buffered reader.

As there are not tests (yet) I went for small commits and tiny steps, so feel free to review commits instead the whole thing at once ;)

Tested once ingame, aka hired a mercenary and then realoaded the game and confirmed I still had a mercenary.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Silly mistrustful Gooey!

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
First of all, I want to thank you for the cleanest PR I have ever seen!

I tried and tried, but can't find any fault with this PR :D I'll wait a couple hours in case someone wants to review this, otherwise I'll do one final play test and merge this.

Oh, and officially welcome to DS :)

**Pull request merged**
