### PR TITLE
Animated menu screen!

### PR DESCRIPTION
**Pull request by vampcat**
Adds a basic implementation for animated menu. This PR only contains "dumb" asteroids for now, but based on feedback, I plan on making the asteroids collide with each other, add ships, and add animated stars.

Feedback would be appreciated.

(Also, I am hoping to get this done before GCI, so there's that.)

### CODE REVIEW

**Comment by vampcat** [comment]
Comments by @ererbe :

```
I just tested out the animated main menu, and its very nice.
But sometimes there is popping up a aseroid in the "middle" of my screen, and this is very weird.
Whats about flying and sometimes slowly rotating but not moving space junk?
and increase the minimum speed of the asteriods a bit, I have a big one that is moving a pixel every 10 seconds or something, but its rotating quite fast.
the color variation is amazing btw, make it looks way more spacy.
is this also ingame? when not: we should do something like this. maybe different types of solar systems:
with a specific sun type (size, color, maybe black hole, white or black dwarf, neutron star... etc)
maybe a color type of asteroids or a "min" color and a "max" color.
And planet types that are generated, and the different enemys like normal.
currently there is just hard and normal...
also sometimes there are popping out in the middle of the screen, this looks very weird.
when there is added a colliding, it should be very rare.
maybe a bit random about the density in general.
```

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by bpas247** [comment]
Is this a duplicate of #387?

**Comment by Adrijaned** [comment]
@bpas247 Yeah, basically. This was here only for reference purpose during GCI, so I'm going to close this now straightaway.

**Pull request closed without merging**
