### PR TITLE
Added some javadocs to SolObject

### PR DESCRIPTION
**Pull request by Adrijaned**
Descriptive and exhausting PR title.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Excellent work! This is a very welcome addition.

**Comment by Cervator** [comment]
Descriptive and exhausting PR response comment espousing great appreciation for moar javadocs!

One outstanding question: default implementations are added for a few things rather than just javadoc. That's a little sneaky. Would any functional impact be likely? I figure not since no other objects implementing the interface are included in this PR, and all prior implemented objects must have already had a method body (thus they'll override the defaults)

Am guessing this is just to make it easier to clean up implementing objects later, and to make it easier to write new ones.

**Comment by Adrijaned** [comment]
Guessing right. :) I tried to fill in some methods with the usually expected defaults.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request closed without merging**
