### PR TITLE
Soundtrack for Steam

### PR DESCRIPTION
**Pull request by Rulasmur**
Added steam script for soundtrack depot.

I've also created the depot on steamworks for it.

- [x] create SteamWorks DLC
- [x] create Depot 
- [x] Convert Music to mp3
- [x] create depot script
- [ ] create Icon for soundtrack
- [ ] pricing?
- [ ] AlbumArtwork.png 400x400
- [ ] licensing

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by msva** [comment]
> - [ ] Convert Music to mp3

But why?

**Comment by Rulasmur** [comment]
@msva That is what steam requires

**Comment by Cervator** [comment]
@NeonInsect did express interest in the past to have the soundtrack released on Steam, just never had a chance to. Interesting that they only support MP3, which is tricky legally. I wouldn't want to have them in the main repo in that format, they're large files too for that matter.

Pricing should be free, license is still held by Neon with us allowed to use it, but not charge for it. Icon/album is one of the new ones we prepared, see https://itunes.apple.com/gb/album/destination-sol-1-ep/id1130523355 for instance :-)

I think we should make a new repo for *all* the Steam stuff, like https://github.com/MovingBlocks/DestSolAndroid and let it be included as a SteamFacade only if you need to work on the Steam stuff.

**Comment by Rulasmur** [comment]
Restored branch as I had forgotten it was still in use

**Pull request closed without merging**
