### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sohil1234**
added space decoration in the main menu

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Adrijaned** [comment]
Please, DON'T USE github upload file feature. It makes our job to review your work immensely harder. Also, you are missing newline at the end of the file.

**Comment by sohil1234** [comment]
actually i was not able to make a pull request in gci branch
therefore i used upload file feature

**Comment by Adrijaned** [comment]
Why didn't you jsut create a new branch?

**Comment by sohil1234** [comment]
i will then create one

**Comment by vampcat** [comment]
Exactly what Adri said - create new branch, and don't use upload feature of github - we'll simply send the task back.

**Comment by vampcat** [comment]
On top of that, you have essentially copy-pasted the changes from my PR. That won't do. It was also mentioned that unless you discuss what we want for this task, we won't accept it. The PR I created had a bunch of comments as well, which are not adressed in your copy-pasting either.

Nope, not reviewing this. Please keep in mind that we are not here to randomly accept tasks which have literally zero effort put into them.

**Comment by vampcat** [comment]
Also, the title of this PR is "added files via upload". This is very disrespectful of the time and effort we mentors (or for that matter, any open source contributor) puts in. As a contributor, it is your job to make it as easy and pleasant as possible for us to review your stuff. Next time, please give your PR a proper title and description, and proper commit names.

**Pull request closed without merging**
