### PR TITLE
Tribe Modification

### PR DESCRIPTION
**Pull request by SurajDatta**
# What is this PR about
This PR is about DESTSOL SHIPS - PART 5: ADD A STATION TO YOUR MODULE, AND MAKE SOME CUSTOM PROJECTILES FOR YOUR WEAPONS
# Changes Made:
- Added new ship texture (since my previous ship was not up to the mark)
- Changed the coordinates and the shape of the ship
- Added a new station
- modified the gun
- shifted my gun from core to tribe (as @vampcat  told me to, because otherwise it wont be counted in the task!)

# Testing
 This PR can be tested by cloning it into your own repo and running it in the game

# Notes
 'w','a','d' to move forward and mouse to change the direction. left click to shoot (if the only one gun) else right and left click to shoot (if 2 guns)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
Okay, so your "icons" are not really icons, they are just the same image. If you go through the wiki page, it's clearly stated that the icons have to be 32x32 black-and-white textures.

Apart from that, your ships rotate *very* weirdly. I have a feeling that's because your ships are not square shaped (they are mostly rectangle). So, change the sprite so that's it a square power of two (32x32, 64x64, 128x128 and so on). To do this, you can just resize the canvas without changing the actual sprite size (so if it's a 73x90 ship, take a canvas of size 128x128 and center the ship in it) and then re-trace the outline in box2d.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
#Changes Made
- Changed the Icons of all the ships to black and white. and resized to 32x32 (Also I couldn't covert the black parts to png)
- Changed the center of rotation of all the ships (except serenityStation)
- Changed the gun location of all the ship (except serenityStation)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
