### PR TITLE
QOL Features

### PR DESCRIPTION
**Pull request by vampcat**
This PR will contain a bunch of extra, quality-of-life changes that hope to deliver a better UX.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Seems like it has potential :-)

I like the idea about the camera adjusting in a way to give the player more visibility - but oddly it seems like it goes the wrong way right now. When I speed up in some given direction my ship gets close to the target direction of travel. Shouldn't it be moving in the opposite direction so you have a little longer to see stuff that's approaching before you run into it?

Bugs noted: problems around entering orbit around a planet / getting close to a surface. I sometimes would see a black corner and one time was missing a surface the first time I approached a planet (maybe that could be some other issue). Saw a planet turret with starry background still.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
Closing for now, since the change can apparently cause motion sickness.

**Pull request closed without merging**
