### PR TITLE
Federal Station

### PR DESCRIPTION
**Pull request by Sigma-One**
# Description
> Added a federal station into the 'hard' system.

# Testing
> Spawn with a Federal Tiny or find the station with any ship.

### Pre Pull Request Checklist:
- [X] There are no errors present in the project
- [X] Code has been formatted and indented

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Sigma-One** [comment]
I'll probably add a weapon, then you can merge

**Comment by Sigma-One** [comment]
I'll probably add a weapon, then you can merge

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Sigma-One** [comment]
Can be merged now.

**Comment by vampcat** [comment]
Tested out, and (obviously) it works perfectly.

The new station is totally amazing. Thanks for the great work :)

**Pull request merged**
