### PR TITLE
Added Slimey faction

### PR DESCRIPTION
**Pull request by Adrijaned**
# Description
> Added Slimey faction, along with the ship Gooey used before he left space adventures and began to rule a more blocky world. His old ship is now however free for you to use for exploring space by yourself, or at least to begin with it. Don't forget to return it to him after you're done, afterwards, he has a lot of memories linked to it!

# Testing
> Happy New Year!

# Notes
> Design's subject to change, however, it's original

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by vampcat** [comment]
I like the idea for the faction, however one small thing is bugging me - the engine looks like it's inside the ship, and I confused the engine fire for the gun fire. Can you shift the engine position, so that it makes more sense?

Also, where did you get the sprite from?

**Comment by Adrijaned** [comment]
The engine's in the ship for a reason, until I get mysefl to draw something more good-looking. And the sprite was drawn by myself, using Krita like you suggested:).

**Comment by vampcat** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
@GooeyHu: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
