### PR TITLE
Deepspace Faction

### PR DESCRIPTION
**Pull request by jasonyonathan**
A new faction consists of new strange and cools alien ships and weapons
:D 

# Description
Added new faction with new cool ships sprites and weapons. All the images are licensed under 
Creative Common Attribution 4.0 International License. All sprites are from MillionthVector (millionthvector.blogspot.id)
# Testing
Just add the module to the game and play :D 

# Outstanding Work
- New Ships and Guns

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by vampcat** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jasonyonathan** [comment]
latest develop ? This repo is just forked last night from movingblocks/destinationsol... how can i check the latest develop ? git fetch and pull ?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by jasonyonathan** [comment]
okay submitting now :D

**Pull request merged**
