### PR TITLE
Syndicate Module

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
# Description
This PR includes the Syndicate Module, which contains various ships and weapons including:
- Syndicate Capital: A mother ship that holds a bazook and a railgun
- Syndicate Large: A large, weak ship than holds a bazook
- Bazook: A slow, expensive rocket launcher that deals 500 damage every 5 seconds

# Testing
> You can these this PR by choosing either of the ships in the starting menu

# Outstanding Work
- [x] Add Syndicate Small
- [x] Add Syndicate Station

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by NicholasBatesNZ** [comment]
- Syndicate Small: a tiny ship that holds a railGun

**Comment by vampcat** [comment]
@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
- Syndicate Medium: A medium ship holding a nailGun
- Syndicate Station: a large station with a passageway just big enough for a Syndicate Capital ship to pass through

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
