### PR TITLE
Fix for issue #5

### PR DESCRIPTION
**Pull request by askneller**
Here is a fix for issue 5. When the ship is in hyper (transcendent) SolGame.myHero is null and replaced in the object manager by a StarPort.Transcendent instance. The loop in MapDrawer does not check for this so I added one.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
Hi @askneller and thanks for the patch! Would you by chance be able to squash some of the extra commits using Git Rebase? If you're not used to / comfortable with that then don't worry about it :-)

Will hope to test it out soon! Will let our bot at it for now

@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/21/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tests out perfectly. Thanks a lot @askneller ! Added you to the credits, hoping to see more code soon :-)

**Comment by askneller** [comment]
Hi and sorry for the late reply. Glad I could help. And sorry about the extra commits, I'll try rebasing in future as you said.

**Pull request merged**
