### PR TITLE
Object manager improvements

### PR DESCRIPTION
**Pull request by Adrijaned**
Various improvements to ObjMan
# Outstanding work:
- [x] Objects need to handle their radii themselves.
- [ ] Javadocs!!!
- [ ] preferably some unit tests (is #268 merged yet?)

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Adrijaned** [comment]
This might turn out useless, since this is one of the things that should be provided by gestalt.

**Pull request closed without merging**
