### PR TITLE
cleanup gestalt module

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
Removing a whole bunch of stuff not needed with latest Gestalt.
~Relies on latest gestalt snapshot being installed locally.~ EDIT: not anymore

https://github.com/MovingBlocks/DestSolAndroid/pull/10

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
@BenjaminAmos would you mind taking a look at this and ensuring I'm not removing anything important? Noteworthy development is that https://github.com/MovingBlocks/gestalt/pull/76 Is in Gestalt 7.0.5
Thanks

**Comment by BenjaminAmos** [comment]
The desktop facade generally runs well with these changes and I could not find any additional issues with the Android facade whilst testing. The removal of the `DestinationSolModuleFactory` class does re-introduce another bug, however I have described how to resolve that issue below.

Code modules in distributions are broken again. I checked this also on the latest `develop` commit (https://github.com/MovingBlocks/DestinationSol/commit/42ec5af80db736a35e3c808c21783af54e46b75b) but it works there, so I believe that the changes made in this pull request may be causing the issue. Whilst assets from modules are loaded correctly, any code within these modules is not initialised.

When examining the debug output, the following lines were present, which I could not find when running a `develop` build:
```
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggSoundFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggMusicFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.emitters.EmitterFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.json.JsonFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.fonts.FontFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.textures.DSTextureFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggSoundFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggMusicFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.emitters.EmitterFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.json.JsonFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.fonts.FontFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.textures.DSTextureFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggSoundInfoFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.audio.OggSoundInfoFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.json.JsonDeltaFileFormat
ERROR [Thread-1] (JavaModuleClassLoader.java:157) - Denied access to class (not allowed with this module's permissions): org.destinationsol.assets.json.JsonDeltaFileFormat
````

After some testing, it appears that this issue occurs when a classpath is detected within the engine archive, as then I think that the engine classes might be re-loaded into the module sandbox. This removes their permissions, leading to the error that occurs. I am still unsure about why this issue only occurrs when the engine is run through the distribution but the initialising the engine module without any specified classpaths appears to fix the issue. I believe that this work-around must have been applied from within the `DestinationSolModuleFactory.createClasspathModule` method. I have submitted #491 which provides these fixes.

I do not believe that the android facade changes change anything functionally with the code. As the sandbox is disabled on Android (Android's java runtime does not support them), removing permissions should not have any effect.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Thanks for bringing this to my attention @BenjaminAmos and thanks also for the PR. I was talking to @immortius (Gestalt author) and he says that changing engine to a package module is a more appropriate solution (see 0317439654d8ebdcfc654e914ebf28622217ce88). The problem at the moment is that everything under `org.destinationsol.*` is exposed to the sandbox, so a refactor of the engine to `org.destinationsol.engine` is needed. I'll leave that as an outstanding issue for now as to not pollute this PR.

**Comment by NicholasBatesNZ** [comment]
This is all in #496

**Pull request closed without merging**
