### PR TITLE
Added org.json dependency and schema validation (using everit-org)

### PR DESCRIPTION
**Pull request by Torpedo99**
# Description
GCI task by Torpedo
This PR replaces the old JSON library with org.json and implements schema validation using everit-org.
This PR is a continuation of #362 and doesn't contain auto formatting of project files. 
# Schema Files to be added
**All schema files are to be added to engine\src\main\resources\assets\schemas**
- schemaColorsConfig,json -> core\assets\configs\colorsConfig
- schemaPlayerSpawnConfig ->playerSpawnConfig.json files
- schemaAbilitiesConfig -> core\assets\configs\abilitiesConfig
- schemaCollisionMesh -> engine:asteroids, engine:miscCollisionMeshes
- schemaSolNames -> engine:planetNamesConfig, engine:systemNamesConfig
- schemaStartingStation -> startingStation.json
- schemaTypes -> core\assets\items\types
- schemaShield -> core\assets\items\shields
- schemaClip -> core\assets\items\Clips
- schemaMazeConfig -> core\assets\configs\mazeConfig,json
- schemaPlanetsConfig -> core\assets\configs\planetsConfig.json
- schemaSystemConfig -> core\assets\configs\systemConfig.json
- schemaSpecialEffectConfig -> core\assets\configs\specialEffectConfig.json
- schemaProjectileConfig -> core\assets\configs\projectileConfig.json

# Schema Files added
- schemaHullConfig.json - #357 
- schemaArmorConfig.json - #357 
- schemaColorsConfig.json - #357 
- schemaStartingStation.json - #357 
- schemaAbilityCharges.json - #365 
- schemaGun.json - #365 
- schemaEngine.json - #365 

# Testing
- Load more schema files
- Start the game
- Play around
- Wait for crash
- If the game crashes, check console for error, if not, play more and have fun!

# Outstanding Work
- Including and testing more schema files.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
This pull request **fixes 1 alert** when merging 4f0419520a1d3fa187be744b5158d7527768142c into f0b11704faf3f5fffe9d9c30c0030f231db34107 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-19763a38c236383435d28f1d7e63a45259f71378)

**fixed alerts:**

* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
This pull request **fixes 1 alert** when merging 661c53a970a43e28fe0e6f535452e7ca6b53490e into f0b11704faf3f5fffe9d9c30c0030f231db34107 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-7cecfdc7ca5a64c377aa1e276eb023254c579b31)

**fixed alerts:**

* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
This pull request **fixes 1 alert** when merging eee670c02583b6626c59108ad648f5d0a9c565d3 into f0b11704faf3f5fffe9d9c30c0030f231db34107 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-2d140c257abadd85155f6f98cf209f5aa277dc24)

**fixed alerts:**

* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Torpedo99** [comment]
Added minor changes requested by @vampcat

**Comment by Cervator** [comment]
This pull request **fixes 1 alert** when merging b1bcbf8c528f77e5968d00d109ed2023fd438d4f into f0b11704faf3f5fffe9d9c30c0030f231db34107 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-a6cb601ae2076eae72d0db875e027a69637e00d7)

**fixed alerts:**

* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Cervator** [comment]
This pull request **fixes 1 alert** when merging ce5e4c3f72172eaf224ed343c5b9041ec744ffaf into f0b11704faf3f5fffe9d9c30c0030f231db34107 - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-00af678e55276e9d07256fc3cad184d760b5494d)

**fixed alerts:**

* 1 for Unused format argument

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by vampcat** [comment]
@GooeyHub : add to whitelist

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Pull request merged**
