### PR TITLE
Console rework / port from Terasology

### PR DESCRIPTION
**Pull request by Mpcs**
# Description
 A lot of changes, I have reworked the console almost completely.
It has most of the functions Terasology has, so tab autocomplete, command history.
I have also ported all the commands already avaiable in DestSol;

~~I'm not sure how commands should return whether it succeded or it wants to propmpt an error. Now it just returns a plain string.~~ Commands can throw CommandExecutionException to prompt an error.

The ParameterAdapterManager is in SolApplication and not in SolGame because SolGame is null when it is needed. Maybe someone has a better idea to where to put it?

### CODE REVIEW

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Thanks so much for this! Merging into a topic branch for now until someone gets time to more thoroughly review it (#472)

**Pull request merged**
