### PR TITLE
Remove TutorialManager access from SolGame

### PR DESCRIPTION
**Pull request by oniatus**
Moves the TutorialManager to context or direct access. I also cleaned up some tutorial-mode checks.

Manual tested:
1. Tutorial mode still starts and tutorial works
2. Tutorial mode does not override existing save

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
This looks really good, however when I start the tutorial and exit immediately, the tutorial elements are still present on continuation of a regular game, and they don't go away when the instructions on them are followed. @Cervator has confirmed that this does not happen in develop.

**Comment by msteiger** [comment]
Code changes look ok to me. Maybe there are more places in the code base that need to be changed? I guess that we should check again after the code conflicts are resolved.

**Comment by Adrijaned** [comment]
Closing with #423 existing now

**Pull request closed without merging**
