### PR TITLE
Fixes a crash when loading a game where the player saved while dead

### PR DESCRIPTION
**Pull request by Steampunkery**
This PR just respawns the player if they try to exit the game while dead, then saves and exits the game.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Steampunkery** [comment]
Well, it just calls the stock respawn function so anything that happens is entirely normal, as far as I can tell.

**Comment by Adrijaned** [comment]
Well just test it for yourself. When respawn is achieved by respawn button, you respawn in the middle of starting base, where you should. When respawning by exit, you respawn _somewhere_

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
Just took this for a spin and it works as advertised.
Merging

**Pull request merged**
