### PR TITLE
Fix for issue #55

### PR DESCRIPTION
**Pull request by askneller**
Added 'myEquipped' flag for items that is saved and read from the prevShip file. Also fixed loss of ammo on save. If a gun has ammo then a clip of it is saved to prevShip.ini.

For testing I altered the prevShip.ini to add a bunch of items then swapped them around, respawned, and checked if all was saved correctly.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Cervator** [comment]
@GooeyHub: add to writelist

@askneller: thanks as usual!

**Comment by Cervator** [comment]
Ahemn .. typo

@GooeyHub: add to whitelist

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/29/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested around some - I'm not sure if it is fully working for me. I added a ton of weaponry in `prevShip.ini` (after having deleted it once to let it regenerate clean just in case) and played around with `imperialBig` and its two heavy slots. When I quit the game it didn't seem like I came back in with the same weapons. Could even leave a slot empty and it would get equipped again?

Maybe an issue with two-slot ships vs single-slot ships?

Please try it out and let me know what you think :-)

Could you also tidy up a few places in the code where if statements lack curly brackets? And avoid * imports, saw one of those in there. Could you also take out `System.out.println("maybeEquip");` from `SolShip.java` ? You didn't add it but the code now spams it like mad when you're talking to a station and maybe just looking at your items :)

Finally if `reEquip` isn't used anymore then just delete it. No need to leave dead code around.

Thanks! :-)

**Comment by askneller** [comment]
Yep I'll fix it.

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/33/
Hooray Jenkins reported success with all tests good!

**Comment by askneller** [comment]
So I believe that I've fixed the issues you mentioned. If any of them are still happening could you give me some more detail please, including the ini file you're using?

Also I couldn't see a `System.out.println("maybeEquip");` in `SolShip.java`, what line number was it?

**Comment by Cervator** [comment]
Huh, I don't see that logging anywhere anymore. Yet it was spamming when I was testing 0_0

Maybe something from an outdated branch somehow. Sorry about that!

Tested it out again, looks very close now :-) Could merge as-is but I noted two oddities:

* If you have no guns equipped and start the game with one or more in your inventory one will still equip (even tried blanking out my inventory completely. starting the game, buying a gun, exiting without equipping, logged in and it was equipped)
* If you only have a secondary gun equipped it'll equip as primary. I figure that's just a consequence of marking things with `*` - can't really tell which is which.

Think those are worth doing anything simple for or nah? I'm fine with merging if not.

If you do change anything feel free to outright delete the `public static void reEquip` method entirely since it isn't in use, along with the commented out use of it. Thanks for the other cleanup!

**Comment by askneller** [comment]
Sorry about the `reEquip`, I completely forgot to delete it.

As to the two issues you mentioned: 
- the first one was intentional as I put it in there to handle the situation where people "upgrade" to this version, as there will be nothing marked as previously equipped in their `prevShip.ini` file. So I figured "may as well equip a gun to begin with". A side effect is that if you unequip everything then save, it'll equip something for you when you load, as you mentioned. 
- You're right it is a consequence of the way I've done it. 

Changing those two wouldn't be much trouble and I'm happy to do it if you want. People will just have nothing equipped the first time they load the new version.

If you do want it changed do you want the same behaviour for `Armor` and `Shield` as well (i.e. nothing equipped initially)?

**Comment by Rulasmur** [comment]
Hey Adam, how hard would it be to switch over from the current setup to numerical slots? Ie, slots 1-100 are equipped items and 101+ are just inventory items.

**Comment by Cervator** [comment]
Probably would be better scoped as a new change with this merged :-)

Unless we just start throwing a number after each activated item instead of a `*` or something super simple

I'm not too worried about a one time "nothing equipped" issue - we can notify about that via release notes :-)

**Comment by Rulasmur** [comment]
Definitely, just reckoned Adam would be the best person to ask at the moment.

**Comment by askneller** [comment]
I don't think it would be too difficult. Unfortunately I wouldn't be able to get to it immediately, so it probably would be better as a separate issue.

**Comment by Cervator** [comment]
Ideally yeah gun 2 stays gun 2 even if gun 1 is unequipped. I'm not too worried about the fine details right now since we probably need to overhaul the inventory/equip system more properly in the near future anyway. So I wouldn't put too much extra effort into it.

This PR as-is offers a nice improvement so I'm happy merging it then continuing with the v1.4.0 release :-)

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/34/
Hooray Jenkins reported success with all tests good!

**Comment by askneller** [comment]
Should be working now. Empty slots stay that way and guns reload to correct slot.

**Comment by Cervator** [comment]
Tried it out real quick, bit short on time tonight :-)

Shield & armor is fine, but if I buy two heavy machine guns from the starting station the 2nd doesn't stay equipped. Both equipped - exit - reload - only primary is equipped. This is with a big imperial. Able to replicate?

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/36/
Hooray Jenkins reported success with all tests good!

**Comment by askneller** [comment]
So that issue was caused by the example `Item`s. I was trying to set the slot on the example item twice and of course only the second time applied. So I copied the example item instead and set the slot on that.

**Comment by Cervator** [comment]
Tested out perfectly now - awesome! Thanks again so much :-)

**Pull request merged**
