### PR TITLE
Waypoint placement fix when rotated

### LINKED ISSUE #557: Waypoints don't set in the proper place when the map is rotated
### How to reproduce:

1. Enter a planet (or sun)'s area of influence.  

2. Try to place a waypoint.  

5. Notice it's in the wrong spot.

### PR DESCRIPTION
**Pull request by AdamJonsson**
# Description
> This PR fixes #557. That is, the waypoint is placed correctly even if the map is rotated. The PR also did some refactoring to extract the "screen click position to world position"-logic and added new tests for this logic.

# Testing
> There exist 9 new tests in [ScreenToWorldMapperNoRotationTest.java](engine/src/test/java/org/destinationsol/screens/ScreenToWorldMapper/ScreenToWorldMapperNoRotationTest.java) and [ScreenToWorldMapperRotationTest.java](engine/src/test/java/org/destinationsol/screens/ScreenToWorldMapper/ScreenToWorldMapperRotationTest.java).
To test if the PR work during gameplay, you can do the following:
* Start a new game.
* Place a marker on the map and see that is placed correctly.
* Go to a planet to introduce rotation of the world.
* Place a marker again and see that it is placed correctly.

# Notes
> **OBS** The commits have a linked issues/PR. These are from the forked repo but GitHub seems to confuse them with the original repo. These linked issue/PR should be ignored.

### Pre Pull Request Checklist:

- [x] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [x] There are no errors present in the project
- [x] Code has been formatted and indented
- [x] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Review by NicholasBatesNZ — APPROVED** [review]
This is a truly beautiful PR. From the separation of logic, to the private method extractions, to the documentation, tests, and of course the fix itself, this really is quality code. We sorely need more like it in the project! Thank you so much and do feel free to stick around and make more contributions in the future :)

**Comment by NicholasBatesNZ** [comment]
Would you mind checking `Allow edits from maintainers` on this PR so that I can resolve the conflicts and get this merged? Or if you're able to resolve them yourself it would be appreciated. Thanks :) image

**Comment by AdamJonsson** [comment]
@NicholasBatesNZ Happy to hear that! :D Could not find the "Allow edits from maintainers", so instead, we made a merge and fixed the conflicts.

**Comment by NicholasBatesNZ** [comment]
Thanks so much :)

**Pull request merged**
