### PR TITLE
started working on engine rework WIP

### PR DESCRIPTION
**Pull request by pollend**
This is abstract factory pattern where the engine dependencies are built by the factory and provided to the engine. we can add additional options to the factory for changing basic configurations between the game starts. It's also possible to also provide a headless configuration in this case for server and test workloads.

This rework also contains a change for for the context. One of the major changes I'm proposing is requiring all the relationships be defined in a service object. this will require that all the relationships be defined beforehand before they are used. The container should handle the problem of instantiating the object and passing into the correct object. This avoids a lot of the problems of tracking when an object is or isn't available. this should work with the existing context.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
This pull request **introduces 1 alert** when merging 02e51d8ff289d37b0ce090bef25f2db77503edf8 into aeea83999b43f235dd3829c9cf834176d330b6bb - [view on LGTM.com](https://lgtm.com/projects/g/MovingBlocks/DestinationSol/rev/pr-1c244f0d24383e072be3b54dc382893145cc557c)

**new alerts:**

* 1 for Container contents are never accessed

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by Cervator** [comment]
Trying to ping @eviltak for a review request but GitHub won't let me :-) There is some injection stuff and context to look at in here.

**Comment by pollend** [comment]
I think we could try rework this to work with koin maybe. Probably preferable to trying to roll out my own DI library.

**Comment by NicholasBatesNZ** [comment]
See #455

**Pull request closed without merging**
