### PR TITLE
Spawn stations

### PR DESCRIPTION
**Pull request by Steampunkery**
# Description
This PR allows each module to set the space station to use when a ship from said module spawns into the game. This is achieved by deleting the `mainStationConfig.json` file and adding a `startingStation.json` file as is shown in the commits. There were also minor modifications to the java files that control spawning in the starting station.

# Testing
Testable by launching the game with these modifications.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
I would usually wait for someone else's review before merging this, but since I've tested this thoroughly and GCI tasks depend on this..

**Pull request merged**
