### PR TITLE
Added a position command

### PR DESCRIPTION
**Pull request by BenjaminAmos**
# Description
This PR adds the ``position`` command into the in-game console. This command simply outputs the position of the player ship. To change to output format, pass the desired format in as a parameter of the command e.g. `position verbose`.
This PR implements the following formats:
- Terse: A minimal, whilst still readable format
```X: 12345    Y: 12345```
- Verbose: A large, readable format, that is easier to understand
```The hero's X co-ordinate is: 12345```
```The hero's Y co-ordinate is: 12345```
- Bold: A format designed for display, it highlights the co-ordinates with a line of asterisks (can be changed) on the lines before and after the X and Y components are displayed.
```*********************```
```X: 12345    Y: 12345```
```*********************```
- Internal: The standard output of ``Vector2.toString()``
```[12345,12345]```

# Testing
- Start a new game. Open the console using the  `` ` `` key. Enter the command ``position``. The player's current position should be outputted to the console.
- Close the console and move the player. Open the console again, issue the ``position`` command and check that the stated position has changed.

# Notes
There is no obligation to accept all the formats, I can just remove the others on request.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by arpitkamboj** [comment]
Excellent work.
Approved the linked task on GCI

@vampcat can decide whether to keep all the different formats or not.

Thanks a lot for your efforts!

**Comment by vampcat** [comment]
@GooeyHub : ok to test

**Comment by GooeyHub** [comment]
Uh oh, something went wrong with the build. Need to check on that

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by Steampunkery** [comment]
Ok looks good from here! Merging.

**Pull request merged**
