### PR TITLE
Fix for issue #56. 

### PR DESCRIPTION
**Pull request by askneller**
If a StarPort's desired position overlaps another port, adjust the desired position. Simple solution for now, can improve if desired.

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by Rulasmur** [comment]
@GooeyHub ok to test

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@Rulasmur: added you to the admin list in Jenkins, should work now :-)

@askneller: thanks!

**Comment by GooeyHub** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.terasology.org/job/DestinationSolPRs/22/
Hooray Jenkins reported success with all tests good!

**Comment by Cervator** [comment]
Tested out and merged! Didn't think I'd be able to easily replicate a situation where starports would have overlapped (seems rare) but the second world I tried placed a pair about as close together as could be without overlap, so I'm thinking that might have been a "fixed" pair :-)

Also to my surprise while testing ran into two big boss ships right by a station - *and they killed it* ! Whole station popped and dropped more loot than I've ever seen. I didn't think they were destructible!

Then the bosses proceeded to murder me quite thoroughly in my newbie ship.

**Comment by askneller** [comment]
Sorry probably should have said in the pull request, if you seed the RNG with the long 8 it will place two starports over each other near one of the planets.

**Pull request merged**
