### PR TITLE
Created Nyancat ship

### PR DESCRIPTION
**Pull request by NicholasBatesNZ**
# Description
This PR adds a much needed ship to the game: Nyancat. This ship includes a custom engine and particles that enable the ship to shoot out rainbow circles and play the Nyancat theme as it moves.
The Nyancat image was supplied by @jellysnake and the sound was clipped from [Elfing on Soundcloud](https://soundcloud.com/elfing/nyan-cat-music)

New engine

# Testing
> You can test this by selecting "Nyancat" as your starting ship

### CODE REVIEW

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by vampcat** [comment]
@GooeyHub: ok to test@GooeyHub: ok to test

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by NicholasBatesNZ** [comment]
I am closing this because:
1. Recent particle changes have broken the module
2. Modules no longer belong here
3. There are many improvements to be made

I have a temporary repo [here](https://github.com/NicholasBatesNZ/DestSolNyan) with the ship

**Pull request closed without merging**
