### PR TITLE
add tribe

### PR DESCRIPTION
**Pull request by SurajDatta**
# Description
> In this pull request, I (Suraj Datta) have made a module (tribe) in which I have added my own custom ships, configs, and items, which can be used in the game and can also be modified! Hope you like it. 

# Testing
> Testing this is in fact very easy, Just copy the code to your personal DestSol file and run it!

# Outstanding Work
- [ ] If there is work still outstanding, please include it here
- [ ] if there is nothing outstanding, remove this section.

# Notes
> Include any extra notes here

### Pre Pull Request Checklist:

- [ ] Code has been scanned with [SonarLint](http://www.sonarlint.org/intellij/)
- [ ] Methods have been annotated with @ Nullable and @ Nonnull ([Read more](https://github.com/MovingBlocks/DestinationSol/wiki/@Nullable-&-@Nonnull-Quickstart))
- [x] There are no errors present in the project
- [x] Code has been formatted and indented
- [ ] Methods have appropriate Javadoc ([How to write Javadoc](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html))

### CODE REVIEW

**Comment by SurajDatta** [comment]
also is serenityEngine.json required?

**Comment by vampcat** [comment]
In your case, it isn't (since you used an engine from the core module - check the serenity.json file if in doubt). Either way, thanks a lot for the PR :)

**Comment by SurajDatta** [comment]
thank you too for helping me

**Comment by vampcat** [comment]
Uhh... there is no need to close the PR, since we will be merging this :D
Just want to get cerv's approval first.

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by vampcat** [comment]
Let's see if I can get the bot to test this..

@GooeyHub: Okay to test

**Comment by Cervator** [comment]
@GooeyHub: ok to test

@vampcat: very subtle difference in the key phrase, I admit :D Not sure it would've worked anyway as you weren't on the admin list for the PR builder yet, but you are now!

@SurajDatta: thanks for the work :-)

So long as the ship works I'm happy, it sounds like the license issue was resolved too. One comment that will be important for future tasks though: Keep an eye out for when a PR like this or other stuff gives you a nice template to fill out. You don't really have a good description for this PR which is a bad practice :-)

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
@Cervator, sorry, I will keep in mind next time.

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by SurajDatta** [comment]
Hi, I have added the serenityMedium for the next task. :)

**Comment by GooeyHub** [comment]
Can one of the admins please verify this patch?

**Comment by GooeyHub** [comment]
Hooray Jenkins reported success with all tests good!

**Comment by vampcat** [comment]
Suraj, what do you use for commiting files to github?

(It seems like it's the web-based file uploader, which is simply not upto the mark for serious changes and has made the history way to messy.)

**Comment by SurajDatta** [comment]
I directly upload

**Comment by SurajDatta** [comment]
myself

**Comment by vampcat** [comment]
I highly recommend that you start using either git CLI, or a proper git GUI. The commits, as they stand, are simply way too messy to understand anything. Try googling around for some git tutorials.

Also, I'll get to this PR shortly.

**Comment by SurajDatta** [comment]
sure,

**Comment by Cervator** [comment]
Please please please use a local Git client. I considered the option to outright ban the usage of GitHub web editing / upload for GCI tasks. It results in a mess and can allow you to bypass a lot of the quality checks you get from working in an IDE.

I suggest reading up on Git and especially how to use topic branches, then make a clean new branch locally, re-commit your work, and re-submit this PR from the other branch. I'm going to close this PR but we'll still review and comment on the content in the GCI task.

**Pull request closed without merging**
